security:
    providers:
        db_provider:
            entity:
                class: App\Entity\ApplicationUser
                property: email
    firewalls:
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\GoogleAuthenticator

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }